project:
  type: website
  output-dir: docs

website:
  title: "Kasia's teaching materials"
  navbar:
    right:
      - about.qmd
      - contact.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css

editor: visual

